ame: Deploy to Xserver via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Deploy to Xserver
      env:
        SERVER_USER: kigekiinc
        SERVER_IP: sv5273.xserver.jp
        SERVER_PORT: 10022
        SERVER_PATH: /home/kigekiinc/akiyoshinishimura.com/public_html
      run: |
        ssh -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USER@$SERVER_IP "mkdir -p $SERVER_PATH"
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -p $SERVER_PORT" --delete ./ $SERVER_USER@$SERVER_IP:$SERVER_PATH

