name: Deploy to Xserver via SSH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_USER: kigekiinc
      SERVER_IP: sv5273.xserver.jp
      SERVER_PORT: 10022
      SERVER_PATH: /home/kigekiinc/akiyoshinishimura.com/public_html

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USER@$SERVER_IP "echo 'SSH connection successful'"

      - name: Deploy to Xserver
        run: |
          ssh -o StrictHostKeyChecking=no -p $SERVER_PORT $SERVER_USER@$SERVER_IP "mkdir -p $SERVER_PATH"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p $SERVER_PORT" --delete ./ $SERVER_USER@$SERVER_IP:$SERVER_PATH/

